kind: pipeline
type: docker
name: default

volumes: # 定义流水线挂载目录，用于共享数据
  - name: maven-service
    host:
      path: /goeasy1.4/
  - name: docker
    host:
      path: /var/run/docker.sock

steps:

  - name: build-package # 流水线名称
    image: maven:3.6.3-openjdk-11 # 定义创建容器的Docker镜像
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: maven-service
        path: /drone/src/service # 将应用打包好的Jar和执行脚本挂载出来
    commands: # 定义在Docker容器中执行的shell命令
      - ls
      - mvn clean package # 应用打包命令
      - ls
      - cp target/hydronedemo-0.0.1-SNAPSHOT.jar /drone/src/service/hydronedemo-0.0.1-SNAPSHOT.jar
      - cp Dockerfile /drone/src/service/Dockerfile
      - cp docker-compose.yaml /drone/src/service/docker-compose.yaml
      - cd /drone/src/service/
      - ls

  - name: build-docker # 流水线名称
    image: plugins/docker:latest
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: maven-service
        path: /drone/src/service # 将应用打包好的Jar和执行脚本挂载出来
      - name: docker
        path: /var/run/docker.sock # 挂载宿主机的docker
    settings:
      username:
        from_secret: docker_registry_username_tencent
      password:
        from_secret: docker_registry_password_tencent
      dockerfile: /drone/src/service/Dockerfile
      repo: ccr.ccs.tencentyun.com/hy-docker-demos/docker-demos
      tags: latest
      registry: ccr.ccs.tencentyun.com
      context: /drone/src/service

  - name: deploy-start
    image: appleboy/drone-ssh # SSH工具镜像
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      command_timeout: 5m # 远程执行命令超时时间
      script:
        - cd /goeasy1.4/
        - docker service rm drone-demo3
        - echo '----rm service----'
        - docker login ccr.ccs.tencentyun.com --username=${docker_registry_username_tencent} --password=${docker_registry_password_tencent}
#        - docker service create --with-registry-auth --publish 8080:8080 --name drone-demo2 ccr.ccs.tencentyun.com/hy-docker-demos/docker-demos:latest
        - docker stack deploy --with-registry-auth --compose-file /goeasy1.4/docker-compose.yaml drone-demo3
        - echo '----start service----'
        - echo '----docker service ps----'
        - docker service ps drone-demo2
        - echo '----docker service ls----'
        - docker service ls
        - echo '----docker node ls----'
        - docker node ls
#  - name: deploy-start
#    image: appleboy/drone-ssh # SSH工具镜像
#    settings:
#      host:
#        from_secret: ssh_host
#      username:
#        from_secret: ssh_username
#      password:
#        from_secret: ssh_password
#      port:
#        from_secret: ssh_port
#      command_timeout: 5m # 远程执行命令超时时间
#      script:
#        - cd /goeasy1.4/
#        - docker stop drone-demo
#        - echo '----stop container----'
#        - docker rm drone-demo
#        - echo '----rm container----'
#        - docker login ccr.ccs.tencentyun.com --username=${docker_registry_username_tencent} --password=${docker_registry_password_tencent}
#        - docker pull ccr.ccs.tencentyun.com/hy-docker-demos/docker-demos:latest
#        - docker run -p 8080:8080 --name drone-demo ccr.ccs.tencentyun.com/hy-docker-demos/docker-demos:latest
#        - echo '----start container1----'